### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Robert50364** [DiamondHoe/cebufit-api#11]
- [x] GetStorageItems by productID (to available)
- [x] MealPrepare -> <list>( Quantity/Weight + <list>stogeItemIds)
- [x] Kurwa
- [x] One ingreadient meal -> od razu eat (np piwo)
- [ ] Oblicznie kosztów posiłków na dany zakres czasu (front 2 dates -> end generate data)
- [ ] Kupione w innej dacie* (optional)
- [ ] user RWS
- [x] Make kategory (front)
- [x] Tworzenie listy zakupów( prosta = zakres czasu all meals ingredients, advanced = to samo - storageItems)
- [x] Fix refresh after add/edit meal
- [x] Add delete meal option (front)
- [ ] Potwierdz eat and make meal (front)
- [x] Recipe descriptions (optional)
- [ ] Modyfikacja usera (KCAL, Name itp)
- [x] Odświeżenie tokena
