### ISSUE TITLE
Ultimate Todo

### ISSUE THREAD

**Issue by Robert50364** [DiamondHoe/cebufit-api#16]
------ TO CHECK------
- [?] Update user data
------------
❗Bugs:
- [ ] #28
- [ ]  Coś źle liczy dla zjedzonych posiłków ( chyba daje całą wartość czy coś)
------------
- [ ] Oblicznie kosztów posiłków na dany zakres czasu (form already on front, but commented, check why) - Norberto back
- [ ] Admin może usuwać produkty z publicznej bazy (to check) - Norberto
------------
- [ ] Shoping list expand bellow add meal - check Robson
-------------
Algorithms:
- [ ] Poprawka pod nowe kategorie + implementacja front
-------------
- [ ] userPage: define height and weight of user FRONT. 50% (form ready, wait for functions)
-------------
Others
-------------
- [ ] Norberto: Dociagnij sobie konstruktory pod C# 12 (Rider power 💪🏻)
-------------
- [ ] Admin panel to manage users - Norberto
-------------
- [ ] Save as new recipe (in meal) FRONT
- [ ] Add based on another (in recipes) FRONT
-------------
- [ ] Summary Page - @DiamondHoe - Poprawki
- [ ] Poogarniać responsywność pod względem wyskakujących paneli z boku - PWA
------------
- [ ] get StorageItems? Past a few prodID and get few one list (less amount of shots to API)
-------------
- [ ] Dark mode FRONT
-------------
- [ ] Wybór języka FRONT
-------------
- [ ] PIWO

------ DONE ------
- [x] Przypomnij hasło

- [x] GetUser details endpoint @Robert50364 

- [x] Public recipes
- [x] Reactive recipe browse
- [x] Reactive category browse
- [x] Reactive product/recipe access (Optional)

- [x] Categories as "type" of product
- [x] product in package or weight flag
- [x] small tables max 4 cols
- [x] recipe view, exapnd szczegóły, 2 view 1 for public one for private

- [x] Porównywanie aktualnego zjedzonego jedzienia do zapotrzebowania (in main page) FRONT

- [x] user RWS:
- [x] #37

- [x] Nie da się dodać receprtury z publicznym produktem, który nie należy do naszego id
- [x] UP: Zerknąć pozostałe public ( Robson na froncie sprawdź i powiedz mi)
- [x] Blokada dat przy rejestracji, (min 5 lat)
- [x] dodać (g) przy produkt unitWeight

- [x] Podpowiedzi na które posiłki są składniki
- [x] Wyliczenie do których posiłków brakuje najmniej składników
